name: Keep Hub Awake

on:
  schedule:
    - cron: '0 */9 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Hub
        env:
          URL_APP: ${{ github.ref == 'refs/heads/main' && 'https://prd-ideias-eventos-jovens-adupno.streamlit.app/' || 'https://dev-ideias-eventos-jovens-adupno.streamlit.app/'}}
          URL_API: ${{ github.ref == 'refs/heads/main' && 'https://joaobarreto27-prd-youth-event-registration-app.hf.space/' || 'https://joaobarreto27-dev-youth-event-registration-app.hf.space/'}}
        run: |
          echo "Pingando o App: $URL_APP"
          curl -L "$URL_APP"
          echo "Pingando a API: $URL_API"
          curl -X GET "$URL_API"
